spring.application.name=ResumeAnalyser



# Set the maximum size for a single file (e.g., 10MB)
spring.servlet.multipart.max-file-size=10MB

# Set the maximum size for the entire request (including all files) (e.g., 15MB)
spring.servlet.multipart.max-request-size=15MB


spring.ai.google.genai.api-key=${GEMINI_API_KEY}

spring.ai.model.chat=google-genai

spring.ai.google.genai.chat.options.model=gemini-2.5-flash